Backend websocket reconnection
openworm/org.geppetto.frontend pull request #902
Opened 2020-02-21 02:18 UTC by ddelpiano

# Backend websocket reconnection

Backend wise, the logic is based on the assumption that we need to save the previous geppetto manager instantiated in the first websocket session since this contains all the information added to the model before the connection will be dropped, differently if we handle only the websocket logic and we reconnect and instantiate a new ConnectionHandler and consequentially a new GeppettoManager this will let us use geppetto to add stuff Ui wise but if we request something that was already supposed to be in the model the whole UI will get crazy (massively out of synch and plenty of geppetto dialogs triggered by cascade errors).

For this reason as soon the onClose method is triggered we check the event status code, if legit we simply remove the project and close this connection, otherwise we save the current GeppettoManager through a set of getter and setter introduced in these changes and we park this a ConcurrentHashMap, stored in the singleton ConnectionsManager.
This is stored with the connectionID as key, so when the frontend will realise that the connection has been dropped will send a reconnect to retrieve the geppettoManager from the previous connection that has been dropped. Here the backend will check if we stored this GeppettoManager, and if present will plug this in the current ConnectionHandler and remove it from the map struct.

Also, when we store the GeppettoManager in the concurrentHashMap, we store also the timestamp in seconds from UTC, everytime a new connection is instantiated we check the connections that have been dropped and now we also check the GeppettoManager parked in memory more than 5 mins, in that case we remove these to avoid to fill up the memory with no remorse.

This address the issue #901 
(the branch has been called fix/177 by mistake since I opened this on the geppetto-client first, if necessary I can rename this).

2020-02-21 15:16 UTC, gidili requested changes
Some cleanup and questions

2020-02-21 15:16 UTC, gidili commented on src/main/java/org/geppetto/frontend/controllers/ConnectionHandler.java
> +		// websocketConnection.sendMessage(requestID, OutboundMessages.EXPERIMENT_LOADING, "");
@dariodippi cleanup?

2020-02-21 15:16 UTC, gidili commented on src/main/java/org/geppetto/frontend/controllers/ConnectionHandler.java
> +				// websocketConnection.sendMessage(requestID, OutboundMessages.EXPERIMENT_LOADED, GeppettoSerializer.serializeToJSON(experimentState));
@dariodippi cleanup?

2020-02-21 15:16 UTC, gidili commented on src/main/java/org/geppetto/frontend/controllers/ConnectionHandler.java
> +	public void setProjectFromId(String requestID, long projectId) {
@dariodippi mixing js vs java bracket styles in this method?

2020-02-21 15:16 UTC, gidili commented on src/main/java/org/geppetto/frontend/controllers/WebsocketConnection.java
> +						// connectionHandler.setProjectFromId(requestID, projectId);
@dariodippi cleanup?

2020-02-25 09:15 UTC, filippomc reviewed
@dario thanks for the explanation, but It's still quite difficult to follow the logic to me, in general there is more complexity than I expected. Probably a sequence diagram would help understand and would be useful to make something on the same line on the Python backend. The main question is: why do we need to recreate the geppetto manager? Isn't it possible to reuse it?

2020-03-03 01:17 UTC, ddelpiano commented
> @Dario thanks for the explanation, but It's still quite difficult to follow the logic to me, in general there is more complexity than I expected. Probably a sequence diagram would help understand 

That is exactly what's happening, we save the geppettoManager and we reload the saved one if the connectionID sent by the client match, differently we create a new one.
I will create a flow diagram tomorrow and will link it here.

> and would be useful to make something on the same line on the Python backend.

Would this be to be applied in https://github.com/openworm/pygeppetto ?
Thx!

2020-03-03 08:44 UTC, Robbie1977 approved these changes

2020-04-24 12:33 UTC, filippomc commented on src/main/java/org/geppetto/frontend/controllers/WebsocketConnection.java
> +					String lostConnectionID = parameters.get("connectionID");
@ddelpiano is this the same value coming as `clientID` after the first connection?
Example from vfb:
`{"type":"client_id","data":"{\"clientID\":\"Connection723\"}"}`

2020-04-24 13:16 UTC, filippomc commented on src/main/java/org/geppetto/frontend/controllers/ConnectionsManager.java
> +			if ((now - value.getRegistration()) > (5 * 60)) {
What about a constant or configuration for the hanging time?

2020-05-26 09:25 UTC, tarelli commented
@filippomc @dariodippi can this one be merged?

2020-05-26 14:17 UTC, filippomc approved these changes

2020-05-26 14:18 UTC, filippomc commented
> @filippomc @dariodippi can this one be merged?
Approved.

2020-05-26 14:49 UTC, merged